
DROP database if exists ALFRED;

CREATE DATABASE if not exists ALFRED;

 USE ALFRED;
 
 CREATE TABLE IF NOT EXISTS CLASSIFICACAO (
    ID_CLASSIFICACAO INT NOT NULL PRIMARY KEY,
    CLASSIFICACAO_INDICATIVA VARCHAR(10)
);
 CREATE TABLE IF NOT EXISTS ATOR (
    ID_ATOR INT NOT NULL PRIMARY KEY,
    NOME_ATOR VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS DIRETOR (
    ID_DIRETOR INT NOT NULL PRIMARY KEY,
    NOME_DIRETOR VARCHAR(50)
);

 CREATE TABLE IF NOT EXISTS FILME (
    ID_FILME INT NOT NULL PRIMARY KEY,
    ID_DIRETOR INT NOT NULL,
    ID_CLASSIFICACAO INT NOT NULL,
	TITULO VARCHAR(50),
    SINOPSE VARCHAR(1000),
    FICHA_TECNICA VARCHAR(100),
    DATA_ESTREIA DATE,
    DATA_RETIRADA DATE,
    FOREIGN KEY (ID_DIRETOR)
        REFERENCES DIRETOR (ID_DIRETOR)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (ID_CLASSIFICACAO)
        REFERENCES CLASSIFICACAO(ID_CLASSIFICACAO)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS ATORES_FILME (
	ID_ATORES_FILME INT NOT NULL,
    ID_FILME INT NOT NULL,
    ID_ATOR INT NOT NULL,
    PRIMARY KEY(ID_ATORES_FILME, ID_FILME, ID_ATOR),
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME(ID_FILME)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(ID_ATOR)
        REFERENCES ATOR(ID_ATOR)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR(9),
    ACESSO ENUM('usuario','adm '),
    EMAIL VARCHAR(50),
    NOME VARCHAR(50),
    LOGIN VARCHAR(50),
    SENHA VARCHAR(50)
    
);


CREATE TABLE IF NOT EXISTS LISTA_DESEJO (
	ID_USUARIO INT NOT NULL,
    ID_FILME INT NOT NULL,
    PRIMARY KEY(ID_USUARIO, ID_FILME),
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME (ID_FILME)
        ON UPDATE CASCADE ON DELETE CASCADE
);




CREATE TABLE IF NOT EXISTS GENERO (
    ID_GENERO INT NOT NULL PRIMARY KEY,
    DESCRICAO_GENERO VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS GENERO_FILME (
	ID_GENERO_FILME INT NOT NULL,
    ID_FILME INT NOT NULL,
    ID_GENERO INT NOT NULL,
    PRIMARY KEY (ID_GENERO_FILME, ID_FILME , ID_GENERO),
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME (ID_FILME)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_GENERO)
        REFERENCES GENERO (ID_GENERO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS HISTORICO (
    ID_USUARIO INT NOT NULL,
    ID_FILME INT NOT NULL,
    PRIMARY KEY(ID_USUARIO, ID_FILME),
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME (ID_FILME)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AVALIACAO(
    ID_USUARIO INT NOT NULL,
    ID_FILME INT NOT NULL,
    NOTA INT,
    primary key(ID_USUARIO, ID_FILME),
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME(ID_FILME)
);


CREATE TABLE IF NOT EXISTS CIDADE (
    ID_CIDADE INT NOT NULL PRIMARY KEY,
    NOME_CIDADE VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS CINEMA (
    ID_CINEMA INT NOT NULL PRIMARY KEY,
    NOME_CINEMA VARCHAR(50),
    ID_CIDADE INT NOT NULL,
    FOREIGN KEY (ID_CIDADE)
        REFERENCES CIDADE (ID_CIDADE)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSAO (
    ID_SESSAO INT NOT NULL PRIMARY KEY,
    SITE_COMPRA VARCHAR(200),
    HORARIO TIME,
    ID_CINEMA INT NOT NULL,
    ID_FILME INT,
    FOREIGN KEY (ID_CINEMA)
        REFERENCES CINEMA (ID_CINEMA)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (ID_FILME)
        REFERENCES FILME(ID_FILME)
        ON UPDATE CASCADE ON DELETE CASCADE
);

       
    






