-- TRIGGER PRA REMOVER DA LISTA DESEJO
DROP TRIGGER IF EXISTS TRIGGER_DELETE_FILME_LISTA_DESEJO;
​
DELIMITER //
CREATE TRIGGER TRIGGER_DELETE_FILME_LISTA_DESEJO BEFORE INSERT ON HISTORICO FOR EACH ROW
BEGIN 
	DELETE FROM LISTA_DESEJO  WHERE ID_FILME = NEW.ID_FILME AND ID_USUARIO = NEW.ID_USUARIO ;    
end; //
DELIMITER ;

-- TRIGGER PRA REMOVER DOS FILMES ASSISTIDOS
DROP TRIGGER IF EXISTS TRIGGER_DELETE_FILME_HISTORICO;
​
DELIMITER //
CREATE TRIGGER TRIGGER_DELETE_FILME_HISTORICO BEFORE INSERT ON LISTA_DESEJO FOR EACH ROW
BEGIN 
	DELETE FROM HISTORICO  WHERE ID_FILME = NEW.ID_FILME AND ID_USUARIO = NEW.ID_USUARIO ;    
end; //
DELIMITER ;
